blueprint:
  name: Thermostat Presence
  description: Set Thermostat to defined temperature if presence state switches.
  domain: automation
  source_url: https://github.com/domrim/homeassistant-blueprints/blob/main/thermostat-presence.yml
  input:
    presence_state:
      name: Presence state
      selector:
        entity:
          domain: input_boolean
    thermostat_target:
      name: Thermostats
      selector:
        target:
          device:
            integration: better_thermostat
          entity:
            integration: better_thermostat
            domain: climate
    idle_temp_helper:
      name: Idle Temperature Helper
      description: The target idle temperature helper
      selector:
        entity:
          domain: input_number
    comfort_temp_helper:
      name: Comfort Temperature
      description: The target comfort temperature helper
      selector:
        entity:
          domain: input_number

mode: queued
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input presence_state
    from: "on"
    to: "off"
  - platform: state
    entity_id: !input presence_state
    from: "off"
    to: "on"
condition: []
action:
  - if:
      - condition: state
        entity_id: !input presence_state
        state: "on"
    then:
      - service: climate.set_temperature
        data:
          temperature: !input comfort_temp_helper
        target: !input thermostat_target
    else:
      - service: climate.set_temperature
        data:
          temperature: !input idle_temp_helper
        target: !input thermostat_target
